// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lodhxqqmwifxfpkoiqvx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxvZGh4cXFtd2lmeGZwa29pcXZ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4NTA5MDIsImV4cCI6MjA3NDQyNjkwMn0.53DezorLqsN5TGJwPE7KmEmoay9287qdBBllC76vdN8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});